steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - app/dockerfile
      - -t
      - $_IMAGE
      - .

images:
  - $_IMAGE

options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s
